# Workflow for Continuous Integration (CI)

name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Run flake8 and pytest
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: module-3-project
          environment-file: environment.yml
          python-version: 3.8.3
          auto-activate-base: false

      - name: Run pytest
        run: pytest -v
