# Workflow for Continuous Integration (CI)

name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Run flake8 and pytest
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: module-3-project
          environment-file: environment.yml
          python-version: 3.8.3
          auto-activate-base: false

      - name: Linting with flake8
        run: flake8

      - name: Run pytest
        run: pytest -v

  deploy:
    name: Deploy to Render
    needs: [build]
    runs-on: "ubuntu-latest"

    steps:
      - name: Deploy to render web service
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
